# https://jekyllrb.com/docs/configuration/options/

title: AlphaHydrae
email: contact@alphahydrae.com
description: Tales of a programmer
url: https://alphahydrae.com # Base hostname & protocol
baseurl: "" # Subpath
github_username: AlphaHydrae
permalink: /:year/:month/:title/

collections_dir: collections
collections:
  archives:
    output: true
  lambda:
    output: true
    permalink: /:year/:month/:title
  today_i_found:
    output: true
  today_i_learned:
    output: true
  today_i_think:
    output: true
  today_i_wrote:
    output: true

# Build settings
plugins:
  - jekyll-email-protect
  - jekyll-feed
  - jekyll-octicons
  - jekyll-postcss
  - jekyll-seo-tag
  - jemoji
  - octopress-image-tag

exclude:
  - bin
  - CNAME
  - docker-compose.yml
  - Dockerfile
  - Gemfile
  - Gemfile.lock
  - .jekyll-cache/
  - node_modules/
  - package.json
  - package-lock.json
  - postcss.config.js
  - README.md
  - tailwind.config.js
  - TODO.md
  - vendor/
