# Site settings
title: AlphaHydrae
email: contact@alphahydrae.com
description: Programming
url: https://alphahydrae.com # Base hostname & protocol
baseurl: "" # Subpath
github_username: AlphaHydrae
permalink: /:year/:month/:day/:title/

collections:
  archives:
    output: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-octicons
  - jekyll-postcss
  - jekyll-seo-tag
  - octopress-image-tag

exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/
