# Site settings
title: AlphaHydrae
email: contact@alphahydrae.com
description: Progamming
url: https://alphahydrae.com # Base hostname & protocol
baseurl: / # Subpath
github_username: AlphaHydrae

# Build settings
theme: minima
plugins:
  - jekyll-feed
  - octopress-image-tag

# Exclude from processing
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
