# Site settings
title: AlphaHydrae
email: contact@alphahydrae.com
description: Progamming
url: https://alphahydrae.com # Base hostname & protocol
baseurl: "" # Subpath
github_username: AlphaHydrae
permalink: /:year/:month/:day/:title/

collections:
  archives:
    output: true

# Build settings
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - octopress-image-tag
sass:
  sass_dir: _sass

# Exclude from processing
exclude:
  - .jekyll-cache/
  - Gemfile
  - Gemfile.lock
  - vendor/
